// songs
let songs = [
  {
    id: 1,
    artist: "Billie Eilish ",
    musicName: "No time to Die",
    path: " https://files.musicfeed.ir/2020/02/Billie-Eilish-No-Time-To-Die-musicfeed.ir_.mp3?128kb",
    cover: "images/1.jpg",
  },
  {
    id: 2,
    artist: "Billie Eilish ",
    musicName: "Everything i Wanted",
    path: " https://files.musicfeed.ir/2019/11/Billie-Eilish-everything-i-wanted-128.mp3",
    cover: "images/2.jpg",
  },
  {
    id: 3,
    artist: "Billie Eilish ",
    musicName: "Happier Than ever",
    path: " https://files.musicfeed.ir/dir/2021/7/Billie%20Eilish%20-%20Happier%20Than%20Ever/Billie%20Eilish%20Happier%20Than%20Ever.mp3",
    cover: "images/3.jpg",
  },
  {
    id: 4,
    artist: "Billie Eilish ",
    musicName: "Listen Before i go",
    path: " http://bayanbox.ir/download/9131075167424378680/Billie-Eilish-listen-before-i-go.mp3",
    cover: "images/4.jpg",
  },
  {
    id: 5,
    artist: "Billie Eilish",
    musicName: "Bad Guy",
    path: " https://dl.baarzesh.net/music/2021/11/Billie_Eilish-_Bad_Guy_320.mp3",
    cover: "images/5.jpg",
  },
  {
    id: 6,
    artist: "Olivia Rodrigo",
    musicName: "Drivers License",
    path: " https://files.musicfeed.ir/dir/2021/5/Olivia%20Rodrigo%20drivers%20license-128.mp3",
    cover: "images/6.jpg",
  },
  {
    id: 7,
    artist: "Parsalip",
    musicName: "Adam Barfi",
    path: " https://dl.melonmusic.ir/1401/Parsalip%20-%20Adam%20Barfi%20[128].mp3",
    cover: "images/7.jpg",
  },
  {
    id: 8,
    artist: "021 - Kid",
    musicName: "Baby Bad",
    path: "https://soundcloud.com/021kid/baby-bad",
    cover: "images/8.jpg",
  },
  {
    id: 9,
    artist: "Poobon",
    musicName: "Bimarefat",
    path: " https://dl.my-ahangha.ir/up/2019/Poobon%20Ft%20Behzad%20Leito%20-%20Bi%20Marefat%20128.mp3",
    cover: "images/9.jpg",
  },
  {
    id: 10,
    artist: "Koorosh",
    musicName: "Shahkare",
    path: " http://dl.shahreahang.com/radiojavan/dey-98/Koorosh-Shahkar%20(Ft%20Sami%20Low%20andamp;%20Pedi%20I)-320.mp3",
    cover: "images/10.jpg",
  },
  {
    id: 11,
    artist: "Billie Illish",
    musicName: "No Time To Die",
    path: ".mp3",
    cover: "images/11.jpg",
  },
  {
    id: 12,
    artist: "Billie Illish",
    musicName: "No Time To Die",
    path: ".mp3",
    cover: "images/12.jpg",
  },
  {
    id: 13,
    artist: "Billie Illish",
    musicName: "No Time To Die",
    path: ".mp3",
    cover: "images/13.jpg",
  },
  {
    id: 14,
    artist: "Billie Illish",
    musicName: "No Time To Die",
    path: ".mp3",
    cover: "images/14.jpg",
  },
];
